language: java
jdk: oraclejdk11

services:
  - docker

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle

before_script:
  mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

jobs:
  include:
    - stage: Build
      script: mvn -B clean compile
    - stage: Test
      script: mvn test -B
    - stage: Deploy To Docker Repository
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build -t cash-manager-api .
        - docker images
        - docker tag cash-manager-api $DOCKER_USERNAME/cash-manager-api
        - docker push $DOCKER_USERNAME/cash-manager-api
    - stage: Restart Docker Container
      script:
        - chmod 400 my-ec2-key-pair.pem
        - ssh -i my-ec2-key-pair.pem -o StrictHostKeyChecking=no ec2-user@18.225.33.122
        - docker run -d -p 4200:8080 $DOCKER_USERNAME/cash-manager-api
