language: java
jdk: oraclejdk11

services:
  - docker

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle

before_script:
  mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

jobs:
  include:
    - stage: Build
      script: mvn -B clean compile
    - stage: Test
      script: mvn test -B
    - stage: Deploy To Docker Repository
      script:
        - docker build -t cash-manager-api .
        - docker tag cash-manager-api 154.49.211.66:32769/cash-manager-api
        - docker images
        - docker push 154.49.211.66:32769/cash-manager-api
