# ===================================================================
# Spring Boot configuration for the "docker" profile.
#
# This configuration overrides the application-docker.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

spring:
  application:
    name: norsysdailycalendarapi
  datasource:
    url: jdbc:mysql://db:3306/cashmanager
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: create

payment:
  maxAttempt: 5