# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overriden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

spring:
  application:
    name: norsysdailycalendarapi
  datasource:
    url: jdbc:mysql://localhost:3307/cashmanager
    username: root
    password:
    dbcp2:
      max-total: 1
    tomcat:
      max-active: 100
      max-idle: 8
      min-idle: 8
      initial-size: 15
      max-wait: 5000
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true

payment:
  maxAttempt: 5