# ===================================================================
# Spring Boot configuration for the "dev" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================
server:
  address: localhost
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/cashmanager
    username: root
    password:
    tomcat:
      max-active: 100
      max-idle: 8
      min-idle: 8
      initial-size: 15
      max-wait: 5000
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true

management:
  security:
    enabled: false

payment:
  maxAttempt: 5