# ===================================================================
# Spring Boot configuration for the "dev" profile.
#
# This configuration overrides the application-prod.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================
server:
  address: localhost
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cashmanager?serverTimezone=UTC
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update

management:
  security:
    enabled: false


